[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
chrono = "0.4.38"
serde = {version = "1.0.203", features = ["derive"]}
ulid = "1.1.2"
argon2 = "0.5.3"
